name: pico_de_oro
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  shared_preferences: ^2.0.5
  change_app_package_name: ^1.0.0
  image_picker: ^0.7.5+3
  sn_progress_dialog: ^1.0.3
  fluttertoast: ^8.0.8
  flutter_masked_text: ^0.8.0
  modal_bottom_sheet: ^2.0.0
  carousel_slider: ^3.0.0
  flutter_image_slideshow: ^0.1.2
  google_maps_flutter: ^2.0.6
  geolocator: ^7.0.3
  location: ^4.1.1
  geocoding: ^2.0.0
  geocoder: ^0.2.1
  intl: ^0.17.0
  flutter_polyline_points: ^1.0.0
  url_launcher: ^6.0.6
  socket_io_client: ^1.0.1
  stripe_payment: ^1.1.4
  flutter_custom_clippers: ^2.0.0



   


  
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

 
  uses-material-design: true

  assets:
     - assets/img/
     - assets/json/





  fonts:
      - family: NimbusSans
        fonts:
          - asset: assets/fonts/NimbusSans/NimbusSanL-Reg.otf

      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto/Roboto-Medium.ttf
